# Generated by Django 5.1.6 on 2025-02-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='seccion',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('niña', 'Niña')], max_length=50),
        ),
    ]
