# Generated by Django 5.1.6 on 2025-02-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_profile_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagen',
        ),
    ]
