# Generated by Django 5.1.6 on 2025-02-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_producto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
