# Generated by Django 5.1.6 on 2025-02-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_producto_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='linea',
            field=models.CharField(choices=[('niña', 'Niña'), ('mujer', 'Mujer')], default='mujer', max_length=10),
        ),
    ]
