# Generated by Django 5.1.6 on 2025-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_orden_pagado_orden_ciudad_orden_comprobante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='precio',
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
