# Generated by Django 5.1.6 on 2025-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_ordenitem_subtotal_alter_ordenitem_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
