# Generated by Django 5.1.6 on 2025-03-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_ordenitem_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='precio',
        ),
    ]
