# Generated by Django 5.1.6 on 2025-03-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_ordenitem_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
