# Generated by Django 5.1.6 on 2025-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_carritoitem_color_alter_carritoitem_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='color',
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='sesion_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='talla',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=2),
        ),
    ]
